project_name: dockerfile

dockers:
  -
    dockerfile: apidoc/Dockerfile
    use_buildx: true
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
    goos: linux
    goarch: amd64
    image_templates:
      - "kuaifan/apidoc:{{ .Tag }}-amd64"
  -
    dockerfile: apidoc/Dockerfile
    use_buildx: true
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    goos: linux
    goarch: arm64
    image_templates:
      - "kuaifan/apidoc:{{ .Tag }}-arm64"
  -
    dockerfile: phpsdwan/Dockerfile
    use_buildx: true
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
    goos: linux
    goarch: amd64
    image_templates:
      - "kuaifan/phpsdwan:{{ .Tag }}-amd64"
  -
    dockerfile: phpsdwan/Dockerfile
    use_buildx: true
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    goos: linux
    goarch: arm64
    image_templates:
      - "kuaifan/phpsdwan:{{ .Tag }}-arm64"
  -
    dockerfile: phpswoole/Dockerfile
    use_buildx: true
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
    goos: linux
    goarch: amd64
    image_templates:
      - "kuaifan/phpswoole:{{ .Tag }}-amd64"
  -
    dockerfile: phpswoole/Dockerfile
    use_buildx: true
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    goos: linux
    goarch: arm64
    image_templates:
      - "kuaifan/phpswoole:{{ .Tag }}-arm64"
docker_manifests:
  - name_template: "kuaifan/apidoc:{{ .Tag }}"
    image_templates:
      - "kuaifan/apidoc:{{ .Tag }}-amd64"
      - "kuaifan/apidoc:{{ .Tag }}-arm64"
  - name_template: "kuaifan/phpsdwan:{{ .Tag }}"
    image_templates:
      - "kuaifan/phpsdwan:{{ .Tag }}-amd64"
      - "kuaifan/phpsdwan:{{ .Tag }}-arm64"
  - name_template: "kuaifan/phpswoole:{{ .Tag }}"
    image_templates:
      - "kuaifan/phpswoole:{{ .Tag }}-amd64"
      - "kuaifan/phpswoole:{{ .Tag }}-arm64"
