name: Build

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  apidoc:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'kuaifan/dockerfile' }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push Docker image kuaifan/apidoc
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: apidoc/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: kuaifan/apidoc

      -
        name: Image digest of kuaifan/apidoc
        run: echo ${{ steps.docker_build.outputs.digest }}

  bakdb:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'kuaifan/dockerfile' }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push Docker image kuaifan/bakdb
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: bakdb/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: kuaifan/bakdb

      -
        name: Image digest of kuaifan/bakdb
        run: echo ${{ steps.docker_build.outputs.digest }}

  compose:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'kuaifan/dockerfile' }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push Docker image kuaifan/compose
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: compose/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: kuaifan/compose:install

      -
        name: Image digest of kuaifan/compose
        run: echo ${{ steps.docker_build.outputs.digest }}

  phpsdwan:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'kuaifan/dockerfile' }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.PERSONAL_TOKEN }}

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push Docker image kuaifan/php:sdwan
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: phpsdwan/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: kuaifan/php:sdwan-8.0.rc11

      -
        name: Image digest of kuaifan/php:sdwan
        run: echo ${{ steps.docker_build.outputs.digest }}

  phpswoole:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'kuaifan/dockerfile' }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.PERSONAL_TOKEN }}

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push Docker image kuaifan/php:swoole
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: phpswoole/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: kuaifan/php:swoole-8.0.rc11

      -
        name: Image digest of kuaifan/php:swoole
        run: echo ${{ steps.docker_build.outputs.digest }}
