name: Build

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Git clone private repo
        env:
          SSH_CONFIG: |
            Host github.com
            HostName github.com
            User git
            IdentityFile /root/.ssh/id_rsa
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_CONFIG" > ~/.ssh/config
          mkdir -p private-repo
          cd private-repo
          git clone -b doo --depth=1 git@github.com:kuaifan/dooso.git
          git clone --depth=1 git@github.com:cossteam/cosslan-tool.git
          git clone --depth=1 git@github.com:cossteam/cosslan-client.git

      - name: Update submodules
        run: |
          git submodule update --init --recursive
          git submodule update --remote --recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        run: |
          chmod +x ./build.sh
          ./build.sh
