name: Sdwan

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:

jobs:
  sdwan:
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags/v')
    strategy:
      fail-fast: true
      matrix:
        php: [ "8.0", "8.1" ]

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Set full names of the Docker image
        id: set_full_names
        run: echo "::set-output name=full_names::kuaifan/php:sdwan-${{ matrix.php }}"

      -
        name: Build and push Docker image kuaifan/php:sdwan-${{ matrix.php }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: phpsdwan/${{ matrix.php }}.Dockerfile
          platforms: linux/amd64,linux/arm64,darwin/amd64,darwin/arm64
          push: true
          tags: ${{ steps.set_full_names.outputs.full_names }}

      -
        name: Image digest of kuaifan/php:sdwan-${{ matrix.php }}
        run: echo ${{ steps.docker_build.outputs.digest }}
